pr: ["master"]

jobs:
  - job: 
    strategy:
      matrix:
        mac:
          imageName: 'macos-10.13'
        # windows:
        #   imageName: 'vs2017-win2016'
    pool:
      vmImage: $(imageName)
    steps:
      - bash: brew install cairo
        condition: eq(variables['Agent.OS'], 'Darwin')

      - template: ci/install-rust.yml
        parameters:
          rust_version: stable

      - bash: |
          export RUST_BACKTRACE=1
          RUSTFLAGS="-D warnings" cargo check --all || exit
          RUSTFLAGS="-D warnings" cargo check --examples || exit
          cargo test --all || exit
          cargo test --examples || exit
        displayName: Run cargo check and test