pr: ["master"]

jobs:
  - job: 
    steps:
      - template: ci/install-rust.yml
        parameters:
          rust_version: stable
      - bash: |
          export RUST_BACKTRACE=1
          RUSTFLAGS="-D warnings" cargo check --all || exit
          RUSTFLAGS="-D warnings" cargo check --examples || exit
          cargo test --all || exit
          cargo test --examples || exit
        displayName: Run cargo check and test