[package]
name = "druid"
version = "0.3.0"
license = "Apache-2.0"
authors = ["Raph Levien <raph.levien@gmail.com>"]
description = "Data-oriented Rust UI design toolkit."
repository = "https://github.com/xi-editor/druid"
categories = ["gui"]
keywords = ["gui", "ui", "toolkit"]
edition = "2018"

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"

[badges]
travis-ci = { repository = "xi-editor/druid" }

[dependencies]
fluent = "0.7.0"
fluent-bundle = "0.7"
unic-langid = { version = "0.4.1", features = ["macros"] }
unicode-segmentation = "1.3.0"

[dependencies.druid-shell]
path = "druid-shell"
version = "0.3.0"
